
-- Sjednocení formátu datumů
UPDATE "tv_program_bez_cyklu"
SET "release_date" = TO_VARCHAR(TO_DATE("release_date", 'DD.MM.YYYY'), 'YYYY-MM-DD')
WHERE "release_date" REGEXP '^[0-9]{2}\\.[0-9]{2}\\.[0-9]{4}$';

-- Změna datových typů sloupců
SELECT "slunec"::DATE "showdate"
    ,"channel"
    ,"time"::TIME "showtime"
    ,"title"
    ,"type"
    ,"short_description"
    ,"year"::INT "year"
    ,"id"::INT "id"
    ,"original_title"
    ,"release_date"
    ,"runtime"::INT "runtime"
    ,"budget"
    ,"genres"
    ,"origin_country"
    ,"original_language"
    ,"production_companies"
    ,"production_company_countries"
    ,"production_countries"
    ,"spoken_languages"
    ,"vote_average"
    ,"vote_count"::INT "vote_count"
    ,"keywords"
    ,"gay_theme"::INT "gay_theme"
    ,"lgbt"::INT "lgbt"
    ,"queer"::INT "queer"
    ,"lesbian_relationship"::INT "lesbian_relationship"
    ,"male_homosexuality"::INT "male_homosexuality"
    ,"closeted_homosexual"::INT "closeted_homosexual"
    ,"transgender"::INT "transgender"
    ,"transsexual"::INT "transsexual"
    ,"drag_queen"::INT "drag_queen"
    ,"coming_out"::INT "coming_out"
    ,"lgbt_teen"::INT "lgbt_teen"
    ,"homophobia"::INT "homophobia"
    ,"gay_marriage"::INT "gay_marriage"
    ,"gay"::INT "gay"
    ,"lesby"::INT "lesby"
    ,"bisexualita"::INT "bisexualita"
    ,"homosexualita"::INT "homosexualita"
    ,"transsexuality"::INT "transsexuality"
    ,"transvestita"::INT "transvestita"
FROM "tv_program_bez_cyklu";